name: Node Continuous Integration
on: push
jobs:
    build-node:
        name: Build Node
        runs-on: ubuntu-latest
        container: node:21.7
        steps:
            - uses: actions/checkout@v4
            - run: node --version
            - run: npm --version
            - run: npm install